### PR TITLE
Add usage examples to README and Text.Regex.TDFA module

### PR DESCRIPTION
**Pull request by williamyaoh**

### CODE REVIEW

**Comment by neongreen** [comment]
Hm, Travis messed up. Hang on, I'll try to fix it.

**Comment by neongreen** [comment]
Please rebase.

**Comment by williamyaoh** [comment]
@neongreen rebased

**Comment by neongreen** [comment]
Thanks!

I made some changes to the Haddock syntax (mainly to provide links to identifiers in code snippets): https://github.com/ChrisKuklewicz/regex-tdfa/commit/e3c15fbf2f8469b0b5b0a09af54aeaabd96024e8

**Comment by neongreen** [comment]
@williamyaoh published! http://hackage.haskell.org/package/regex-tdfa-1.2.3.2/docs/Text-Regex-TDFA.html

**Comment by williamyaoh** [comment]
🎊 🎊 🎊

**Pull request merged**
