### PR TITLE
Supported GHC 8.8.1

### PR DESCRIPTION
**Pull request by asr**
This PR fix compilation with GHC 8.8.1.

### CODE REVIEW

**Comment by asr** [comment]
Thanks for merging. Please release a new version on Hackage.

**Comment by neongreen** [comment]
I will after https://github.com/ChrisKuklewicz/regex-tdfa/pull/28 passes.

**Comment by neongreen** [comment]
Released regex-tdfa-1.2.3.3.

**Comment by neongreen** [comment]
Update: you should use 1.3.0, not 1.2.3.3. See https://github.com/ChrisKuklewicz/regex-tdfa/issues/29.

**Pull request merged**
